

columns = ["Nama Produk",
           "Deskripsi Produk",
           "Kode Kategori",
           "Berat (Gram)",
           "Minimum Pemesanan",
           "Nomor Etalase",
           "Waktu Proses Preorder",
           "Kondisi",
           "Foto Produk 1",
           "Foto Produk 2",
           "Foto Produk 3",
           "Foto Produk 4",
           "Foto Produk 5",
           "URL Video Produk 1",
           "URL Video Produk 2",
           "URL Video Produk 3",
           "SKU Name",
           "Status",
           "Jumlah Stok",
           "Harga (Rp)",
           "Kurir Pengiriman",
           "Asuransi Pengiriman"
           ]
